[package]
name = "ndotter_backend"
version = "2.0.0"
authors = ["Koncepto Sociala"]
description = "Convert bitmaps to N-dot SVG art"
license = "MIT"
edition = "2021"

[dependencies]
image = "0.25.3"
open = "5.3.0"
svg = "0.18.0"
thiserror = "1.0.64"
