[package]
name = "ndotter_cli"
version = "2.0.0"
authors = ["Koncepto Sociala"]
description = "CLI frontend for ndotter"
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
ndotter_backend = { path = "../backend"}